### PR TITLE
Fixes #3 Pandoc builds an ePub

### LINKED ISSUE #3: Spike using Pandoc to build an ePub/Mobi
Goals:

* Have a better idea how to organize the content in the repo
* Have a better idea in what Pandoc can do for us around glossaries, tables of contents, and index's

### PR DESCRIPTION
**Pull request by zspencer**
@jessicard This adds two make tasks:

`make build` which will create an epub and `make open` which will open the ePub in your default eReader for review.

### CODE REVIEW

**Comment by zspencer** [comment]
Annndddd HTML is easier than I thought Yay!

**Comment by zspencer** [comment]
By default, pandoc inserts a table of contents. We'll want to figure out how to build in a glossary as well as  an index of words used in the glossary; but I think that's a challenge for another day.

**Comment by zspencer** [comment]
screen shot 2015-03-16 at 12 44 35 am

**Comment by zspencer** [comment]
Fixes #3

**Comment by jessicard** [comment]
This works now! I moved the blog posts from /src to /en-US/src - is this the right move? Also, should we be pushing up an empty output folder? Pandoc errors without it, but we don't want to push up the epub. Thoughts?

Other than that, this is ready to merge!

**Comment by zspencer** [comment]
:+1: 

Re: Output folder - Good question! Maybe a `output/.gitkeep` file which is force-added (`git add -f output/.gitkeep`, I think)

**Comment by jessicard** [comment]
@zspencer Thanks! Added the folder, merging this now :)

**Pull request merged**
