### PR TITLE
Pull out "The Terminal" section into a chapter

### PR DESCRIPTION
**Pull request by jessicard**

### CODE REVIEW

**Comment by jessicard** [comment]
I don't like this chapter the way it is. Not enough information about what the terminal *is*, I think. Very open to suggestions @zspencer & @kmanion!

**Comment by jessicard** [comment]
I'm going to pull out the home directory and root references into another chapter about file structure I think.

**Comment by zspencer** [comment]
We may want to include a few commands to help people get situated. Like `pwd` tells you where you are and `ls` shows you what is in the current directory.

Part of me thinks a reasonable analogy to use may be that directories are like rooms; and in those rooms are things you can interact with.  We could extend this to say that your "home directory" is a wing of a house that is all yours. For example:

Think of your computer as a mansion, with many many many wings and rooms. This mansion is known as your computers "file system." When you open up the terminal, it starts out in the entrance hall to your private wing of the mansion; known as your "home directory." The home directory is represented by `~` (tilde). It even looks like a hallway! Just more squiggly! To see where your home directory is in relation to the entrance to this giant mansion, we run the command `pwd`. You should see something like `/Users/<your-user-name>`. The first `/` is the entrance to your mansion or the very-top-level of your computers file system. This is known as the "root" directory. `Users` is where every user's home directory is stored.  (If you're using linux, you will see `home` instead of `Users`). 

To see what's in the room with you, run the command `ls` which stands for "list directory contents". Some of these items are files, and some are other directories. To see more clearly which are which, you may add the flag `F` to the `ls` command like so:  `ls -F`.

Look at that! Some of the listed items have a `/` (slash) after their name! This tells us the item is a directory. Who knows what's in that directory! Perhaps buried treasure! Perhaps adorable puppy gifs! Perhaps the cover sheet for that TPS report we forgot to file... To find out we can pass the name of the directory into the `ls` command: `ls -F <name-of-a-directory>`

**Comment by zspencer** [comment]
Oops, this comment should have been left on the File System PR :). 

Re: Why the terminal, we should start with why the person wants to use the terminal. I use the terminal to

- Tell my computer to do things aren't available through a GUI; i.e. it gives me more power over my computer; as I don't have to rely on other people to build programs for me to do X or Y. Mouse-based interactions are far more usable; but text-based command line interfaces are much more flexible 
- Increase the speed at which I can explore and interact with my computer.  Mouse base interactions rely on my ability to hit the right bounding box click a drop down, etc. Terminal based interactions allow me to interact at the speed of thought (or type :))

Re: What is the terminal? 
- It's a portal to your computers internals. All the flash and glamour of the fancy pants UIs are stripped away and all that's left is *you* and *your machine*. 
- It's intimidating. That portal looks like the entrance into some kind of techno-hell. Black text. White background. Cryptic symbols. Mice and touch based UIs are comforting and convenient. However, they are very limited in how they can be composed. (See, drag and drop between applications). The command line is *infinitely composable*

**Comment by zspencer** [comment]
We may want to figure out a way to differentiate between the *terminal* and the *command line* or mayb enot.

**Pull request closed without merging**
